---
title: Curriculum Vitae
css: styles.css
---

Updated April 2025

<a href="cv.pdf" style="text-decoration: none;">
<button style="background-color: black; color: white; padding: 10px 20px; font-size: 16px; border-radius: 5px; font-family: 'Oswald', sans-serif; display: block; margin: auto;">
Download CV </button> </a>

# **RESEARCH INTERESTS**

·Infectious diseases and bacterial pathogenesis

·One Health

·Parasitology

·Invertebrates

·Cell and Molecular Biology

·Eukaryotic Cellular Biology

·Morphology

·Tick control

·Natural products and biological control

·Propagation and study of tick-borne pathogens in tick cell and organ
cultures

·Use of tick cell lines as tools for the study of tick biology,
physiology, and control

·Tick and Tick-borne diseases

## PROFESSIONAL APPOINTMENTS

·**March/2022 – present: Acadia University, Wolfville, NS, Canada.**

·Postdoctoral Researcher, Department of Chemistry and Biology.

As a Postdoctoral Fellow at Acadia University, my role focuses on
advancing innovative research in tick management. This includes the
development of novel repellents and acaricides utilizing natural
compounds and microorganisms. I collaborate with companies such as
AtlanTick and Maskwiomin to enhance their products and collect data
necessary for registering these products with the Pest Management
Regulatory Agency in Canada. Additionally, I utilize my neurobiology
experience to evaluate how ticks respond to chemical stimuli,
contributing insights into their host-seeking behaviours and reactions
to repellents. I have successfully led projects to create plant-based
tick repellents and acaricides, showcasing my project management and
leadership abilities. My responsibilities also encompass designing and
conducting bioassays to assess product efficacy using advanced
analytical methods like HPLC, GC-MS, nanoparticle analysis, molecular
biology, and microscopy. Effective collaboration with colleagues from
diverse departments, such as Chemistry and Biology, has propelled
research efforts toward shared objectives. Moreover, I mentor research
associates to improve their skills, enhancing our lab's productivity. I
have demonstrated strong organizational capabilities and a commitment to
deadlines, producing high-quality research reports and presentations
vital for securing funding and disseminating our research findings.

·**July/2020 - February/2022: Brazilian Agricultural Research
Corporation (EMBRAPA Southeastern Livestock, Brazil), São Carlos, SP,
Brazil**.

·Postdoctoral Researcher, Veterinary Parasitology Laboratory.

As a Postdoctoral Researcher at Embrapa, I gained extensive experience
in tick research and management within a corporate setting. I
collaborate with companies such as Decoy to enhance their products and
collect data necessary to register them with Brazil's Ministry of
Agriculture, Livestock and Food Supply. I successfully led a project
that resulted in a patented solution for controlling cattle ticks,
showcasing my ability to drive innovative research and development by
integrating Biology, Animal Physiology, Chemistry, Nanotechnology, and
Pest Management. My expertise covers a wide range of techniques,
including microscopy (histology, histochemistry, immunohistochemistry,
scanning electron microscopy, transmission electron microscopy, and
confocal laser microscopy), molecular biology (DNA extraction, PCR,
qPCR), and animal handling. I deeply understand tick biology,
encompassing their morphology, physiology, and behaviour. I have
effectively conducted toxicological analyses of natural products to
evaluate their efficacy against ticks and their potential impact on
livestock. In addition, I have experience in cultivating tick cells in
vitro, offering valuable insights into their biology and possible
targets for control strategies. My capacity to plan and execute
bioassays has been crucial in assessing the effectiveness of tick
control methods. I have also implemented biological control to create
sustainable and integrated tick management strategies. Throughout my
tenure at Embrapa, I have consistently exhibited strong research skills,
including data analysis, report writing, and scientific communication.
My contributions to the field have been acknowledged through the
publication of scientific papers and the development of a patented
technology.

·**Jan/2020 – June/2020: Eurofins Brazil Environment Testing, Rio Claro,
SP, Brazil.**

·Analytical Services Specialist I, Analytical Service Manager.

As an Analytical Services Specialist at Eurofins, I played a crucial
role in ensuring the accuracy, timeliness, and compliance of
environmental analysis reports. I was responsible for evaluating data
and preparing comprehensive reports for a wide range of parameters,
including physical-chemical, microbiological, organic, inorganic, and
toxicological analyses in environmental matrices such as water,
effluents, soils, sediments, residues, and atmospheric emissions. I
maintained a strong focus on customer satisfaction, delivering
exceptional service throughout the entire analysis process. My
responsibilities included monitoring sample progress, promoting the use
of online systems for sample registration and report access, and
providing technical support to clients. My expertise in environmental
analysis and commitment to quality assurance enabled me to deliver
reliable and accurate results that met the stringent requirements of the
ABNT NBR ISO/IEC 17025 standard.

·**Aug/2017 – Dec/2017: São Paulo State University, Rio Claro, SP,
Brazil**

·Adjunct professor

As an Adjunct Professor (contracted limited term) at UNESP, I
successfully designed and delivered lectures, seminars, and laboratory
sessions for the course "Aging and Cell Death." My primary focus was
enhancing student learning outcomes and fostering a stimulating and
engaging learning environment. The course examined the fundamental
concepts of aging theories, their purposes, and their impacts on various
cell types. I covered topics such as cardiovascular deterioration,
neural loss, age-associated diseases, and the role of cellular
structures in aging. Additionally, I explored the different types of
cell death, including apoptosis, autophagy, and necrosis, using both
morphological and molecular approaches. I encouraged active
participation through seminars and class discussions to deepen student
understanding. These sessions provided opportunities for students to
examine the environmental influences on aging, discuss physiological and
anatomical changes, and connect course content to their daily lives.

·**Apr/2015 – May/2019: São Paulo State University, Rio Claro, SP,
Brazil**

·Laboratory Manager

As a Laboratory Manager (PhD student) at UNESP, I managed the operations
of a research laboratory focused on tick control. My responsibilities
included overseeing a team of undergraduate and graduate students,
ensuring the proper maintenance and calibration of laboratory equipment,
and maintaining tick colonies following ethical guidelines. I played a
crucial role in designing and conducting bioassays to assess the
efficacy of natural products against ticks. My expertise in microscopy
techniques, including histology, histochemistry, immunohistochemistry,
scanning and transmission electron microscopy, and confocal microscopy,
allowed me to analyze samples at a cellular level. I successfully
extracted RNA and DNA from various samples, facilitating downstream
molecular analysis. My proficiency in PCR and qPCR techniques enabled me
to amplify and quantify specific DNA sequences. Additionally, I ran
electrophoresis gels to visualize and analyze DNA and RNA fragments. I
maintained in vitro cultures of invertebrates (ticks) and mammalian
cells, monitoring their viability and growth under aseptic conditions.
Alongside my research activities, I trained and mentored students and
fostered a positive and productive learning environment. Furthermore, I
demonstrated strong organizational skills and a commitment to meeting
deadlines, ensuring the timely completion of research projects and the
production of high-quality reports.

·**Oct/2018 – Jan/2019: University of Liverpool, Liverpool, UK**

·Honorary Research Assistant

As an Honorary Research Assistant at the University of Liverpool, I
investigated the effects of natural products on tick cell lines. My
research focused on populations of Rhipicephalus microplus exhibiting
varying levels of acaricide resistance. I gained valuable experience in
tick cell culture techniques and light microscopy, specifically in
histology and histochemistry. My responsibilities included preparing
solutions, culture media, samples, and slides for toxicological analysis
and histological staining. I also designed and conducted bioassays to
evaluate the toxicity of natural products on tick cells, analyzing the
results and reporting my findings. Through my research, I developed
skills in biostatistics, interpersonal communication, presentation,
technical writing, and collaborative problem-solving. My contributions
to the research team were crucial in advancing our understanding of tick
biology and potential natural product-based control strategies.

# **EDUCATION AND RESEARCH TRAINING**

------------------------------------------------------------------------

**2019. PhD in Cell and Molecular Biology**. São Paulo State University,
Brazil, with a collaborative period in the *Tick Cell Biobank*
laboratory from the **University of Liverpool, UK**, under Dr Lesley
Bell Sakyi's supervision. **Research project:** “Acaricidal activity *in
vitro* of spilanthol against cell lines derived from acaricide-resistant
and acaricide-susceptible *Rhipicephalus microplus* ticks with or
without *Ehrlichia minasensis* infection.” **Dissertation:** The
acaricide action of Jambu (*Acmella oleracea*): Study of the effects on
morphophysiology of male and female reproductive systems of *Amblyomma
cajennense* (Fabricius, 1787) (Acari: Ixodidae) ticks. Advisor:
Professor Dr Maria Izabel Camargo-Mathias

**2015. MPhil in Cell and Molecular Biology**. São Paulo State
University, Brazil

**Thesis:** Effect of the extract of salivary glands of female
*Rhipicephalus sanguineus* (Latreille, 1806) on inhibition and
proliferation of tumour cells. Advisor: Professor Dr Maria Izabel
Camargo-Mathias.

**2013. Licentiate degree in Biological Sciences (Honours –
education).** São PauloState University, Brazil. **Honours thesis:**
“Analysing the movie Antz as a resource for science education.” Advisor:
Professor Dr José Euzébio de Oliveira Souza Aragão.

**2012. BSc in Biological Sciences (Honours)**. São Paulo State
University, Brazil. **Honours thesis**: “Testes of fed and unfed
*Amblyomma cajennense* ticks (Acari: Ixodidae). First morphological
data”. Advisor: Professor Dr Maria Izabel Camargo-Mathias.

# **AWARDS**

**2023:** XIV Brazilian Symposium of Pharmacognosy, Maranhão,
Brazil**.** Best oral presentation.

**2022-2023:** Research Internships Abroad (BEPE) Postdoctoral fellow –
FAPESP, Embrapa, São Paulo, Brazil / Acadia University, Canada.

**2020-2023:** Postdoctoral fellowship award (FAPESP), Embrapa, São
Paulo, Brazil.

**2018-2019:** Research Internships Abroad (BEPE) PhD – FAPESP, São
Paulo State University, São Paulo, Brazil / University of Liverpool, UK.

**2015-2019:** Ph.D. scholarship (FAPESP) in Cell and Molecular Biology,
São Paulo State University, São Paulo, Brazil.

 **2013-2015:** Master's scholarship (FAPESP) in Cell and Molecular
Biology, São Paulo State University, São Paulo, Brazil.

# **TEACHING EXPERIENCE**

## **Courses taught**

Aging and Cell Death(Biological Science undergraduate program), São
Paulo State University, Brazil, 2017 (1 semester).

## **Teaching assistantships**

Histology course – Biological Science program – UNESP- Brazil (2014 –
2016) (2 semesters)

Cell Biology course – Biological Science program – UNESP- Brazil (2015 –
2015) (1 semester)

Functional Histology course – Biological Science program – UNESP- Brazil
(2015 –2015) (1 semester)

## **GUEST LECTURER**

### **Graduate program:**

[**Veterinary Sciences - São Paulo State University – Jaboticabal
Campus**]{.underline}

**Alternative Control of Cattle and Sheep Parasites: Current Affairs and
Practices course –** Morphology and electrophysiology as tools in tick
control studies on 9 September 2024.

[**Veterinary Sciences - São Paulo State University – Jaboticabal
Campus**]{.underline}

**Alternative Control of Cattle and Sheep Parasites: Current Affairs and
Practices course –** Morphology and electrophysiology as tools in tick
control studies on 30 May 2023.

[**Veterinary Sciences - São Paulo State University – Jaboticabal
Campus**]{.underline}

**Alternative Control of Cattle and Sheep Parasites: Current Affairs and
Practices course -** Morphology as a tool in toxicological studies in
ticks on 15 February 2022.

### **Undergraduate program:**

[**Biology course – Environmental Science program**]{.underline}

**Prokaryotic and Eukaryotic Cells** on April 4, 2016

**Bacteria** on May 18, 2015.

**Fungi** on May 25, 2015.

**Cell visualization and microscopy** on 21 May 2016.

**Prokaryotic and Eukaryotic Cells** on March 10, 2014.

[**Histology Course – Biology program**]{.underline}

**Blood Cells** on April 1st, 2015.

**Adipose Tissue** on November 10, 2015.

[**Developmental Biology: Regulatory Mechanisms course – Biology
program**]{.underline}

**Sex determination mechanisms involving genetic and environmental
factors (intrinsic and extrinsic)** on April 7, 2016.

**Initial development of multicellular organisms: universal mechanisms
of development and genesis of the body plane** on April 28, 2016

**Assembly of histological slides and photo documentation in
bright-field microscope** on 16 June 2016.

[**Cell Biology course – Biology program**]{.underline}

**Cell staining and visualization techniques**, on June 12, 2015.

## **WORKSHOPS**

**ANHOLETO, LUÍS ADRIANO**; CAMARGO-MATHIAS, M. I. DELALIBERA JR, I.
OLIVEIRA, P. R.; TRAVAGLINI, R. V.; D'ALESSANDRO, C. P.; DINIZ, A.;
ALVES, G. R. Biological Control applied to pests and vectors of
zoonoses, carried out at UNESP of Rio Claro, SP, in the period from 11
to 12 July 2018.

**ANHOLETO, L. A.** Fundamentals of Histology and Light Microscopy at
UNESP, Rio Claro, SP, from January 25 to 27, 2016.

## **MENTORING ACTIVITIES**

### **Graduate students**

Melissa Carolina Pereira, MSc, São Paulo State University, 2021
(Co-advisor)

### **Undergraduate students**

Jaclyn Delahunt – research topics 2025, Acadia University, Canada
(Co-supervisor).

Kennedy Jefferson – research topics 2024, Acadia University, Canada
(Co-supervisor).

Leilia Fraser – Summer student 2024, Acadia University, Canada
(Co-supervisor).

Creighton Jarvis - Summer student 2024, research topics 2024, 2025,
Acadia University, Canada (Co-supervisor).

Bronwyn Naugler - Summer student 2024, Acadia University, Canada
(Co-supervisor).

Sophia Blanchard - Summer student 2023, Acadia University, Canada
(Co-supervisor).

Thais Scopinho Ceccato, BSc, Honour Thesis, 2021 (Co-advisor)

### **High School students (Community outreach)**

Eduardo Lopes da Silva, Research Internship, Public School EE Chanceler
Raul Fernandes, 2019 (Advisor).

Lara Lima Bertola, Research Internship, Public School EE Chanceler Raul
Fernandes, 2019 (Advisor).

Julia Roccon Tomaz, Research Internship, Public School EE Marciano de
Toledo Piza, 2019 (Advisor).

# **COMMUNITY OUTREACH**

[**Community project:**]{.underline}

Organizer of First Steps in Science. 2017. *Founder of the Project*. São
Paulo State University, Brazil.

Organizer of First Steps in Science. 2016. *Founder of the Project*. São
Paulo State University, Brazil.

[**Guest lecturer:**]{.underline}

**High School:**

**“Fundamentals of Cell Biology and Microscopy**,” on June 10, 2016, to
the students of the 2nd grade of the High School of the State School
Prof. Délcio Báccaro.

**“Cells Closely: An Introduction to Light Field Microscopy**,” held
together with the thematic course "From Mendel to Modern
Biotechnological Applications, An Update for Teachers and High School
Students," on October 22, 2016, at UNESP Rio Claro, SP.

**“The microscope as a tool for the study of the cell"** in the
community project "IV First Steps in Science," promoted by the Cellular
and Molecular Biology Graduate Program at UNESP Rio Claro.

**“Cells up close, from the cytoplasm to nucleus: everything you’ve ever
wanted to know (and see) about the smallest components of living
beings**,” taught in the extension project "First Steps in Science, held
at UNESP Rio Claro, SP, from July 3 to 7, 2017.

**“Getting to know UNESP Rio Claro: practical activity of microscopy,”**
carried out on April 23, 2019, at UNESP Rio Claro, SP, as part of the
activities of the Week of the Worker, carried out by the School Company
Integration Centre - CIEE.

**“Unity and diversity: the cell closely”** was taught in the "First
Steps in Science" community project, held at UNESP Rio Claro, SP, from
July 4 to 8, 2016.

# **THESIS COMMITTEE MEMBER**

Bianca Augusto de Souza (UFRRJ), Master\`s thesis, Brazil, 2024.

João Vitor Carvalho Constantini (UNESP), Qualifying Examination for
Master's Degree, Brazil, 2023

Leonardo Aparecido Lima dos Santos (UNESP), Master’s thesis, Brazil,
2023

Ana Victória Gonçalves (UNESP), Honours Thesis, Brazil, 2021

Cleiton Pereira de Souza (UNESP), PhD candidate, Brazil, 2019

# **PUBLICATIONS (PEER-REVIEWED)**

## **Journals**

**1.** GAUDET, K..; **ANHOLETO, LA.**; HILLIER, N.K.; FARAONE, N.
Lemongrass essential oil and DEET inhibit attractant detection in
infected and non-infected *Ixodes scapularis* ticks. Current Research in
Insect Science, v. 6, p. 100096, 2024.

**2.ANHOLETO, L.A.**; BLANCHARD, S.; WANG, H.V.; CHAGAS, A.C.S.;
HILLIER, N.K.; FARAONE, N. *In vitro* acaricidal activity of essential
oils and their binary mixtures against *Ixodes scapularis* (Acari:
Ixodidae). Ticks and Tick-Borne Diseases, v. 15, p. 102309, 2024.

**3.ANHOLETO, L.A**.; BRANCAGLION, G.A.; SANTOS, D.M.; KAPRITCHKOFF,
R.T.I.; CASTRO, K.N.C.; CANUTO, K.M.; RODRIGUES, R.A.F.; CORREA, D.S.;
CHAGAS, A.C.S.; PASTRE, J.C. Acaricidal activity of synthetic spilanthol
derivative against ticks of medical and veterinary importance.
Veterinary Parasitology, 2024.

**4.** CEPEDA, D.F.; ASCARI, J.; OLIVEIRA, M.S.; ANTONIOLI, G.;
BARCELLOS, T.; **ANHOLETO, L.A.;** NUNES, P.H. Effect of *Tagetes
minuta* essential oil on the central nervous system of unfed
*Rhipicephalus sanguineus* sensu lato tropical lineage’ ticks.
Experimental And Applied Acarology. v.1, 2023.

**5.** SILVA, I.S.; VALE, L.; COUTINHO, A.L.; SOUSA, L.J.M.P.;
MARCHESINI, P.; MATOS, R.S.; **ANHOLETO, L.A.;** CAMARGO-MATHIAS, M.I.;
FERREIRA, L.L.; ARRUDA, W.; MONTEIRO, C. Thymol and eugenol against
*Rhipicephalus sanguineus* sensu lato engorged females: biological,
histopathological and bioinformatic analysis. Veterinary Parasitology,
v. 319, p. 109938, 2023.

**6.** SANTOS, I.B.; FERREIRA, A.U.C.; RABELO, M.D.; **ANHOLETO, L.A.;**
SOUSA, G. A.; GAÍNZA, Y. A.; FIGUEIREDO, A.; ESTEVES, S. N.; CHAGAS,
A.C. S. Portable near-infrared spectroscopy: A rapid and accurate blood
test for diagnosis of *Haemonchus contortus* infection and for targeted
selective treatment of sheep. International Journal for Parasitology.
v.53, p.119 - 127, 2023.

**7.** FIGUEIREDO, A.; **ANHOLETO, L.A.;** COLA, D.F.; FANTATTO, R.R.;
GAINZA, Y.A.; SANTOS, I.B.; VIÇOZZI, G.P.; ÁVILA, D.S.; FRACETO, L.F.;
CHAGAS, A.C.S. Acaricides containing zein nanoparticles: A tool for a
lower impact control of the cattle tick *Rhipicephalus microplus*.
Veterinary Parasitology, v. 318, p. 109918, 2023.

**8.** PEREIRA, M.C.; **ANHOLETO, L.A.**; KASA, G.G.; CASTRO, K.N.C.;
CANUTO, K.M.; SOUZA, A.S.Q.; CAMARGO-MATHIAS, M.I. Efficacy of essential
oils of *Egletes viscosa* and *Lippia schaueriana* on the reproductive
biology of *Rhipicephalus sanguineus* sensu lato engorged females.
Experimental Parasitology, v. 244, p. 108423, 2023.

**9.** FIGUEIREDO, A.; **ANHOLETO, L.A.;** COLA, D.F.; FANTATTO, R.R.;
SANTOS, I.B.; GAINZA, Y.A.; SOUSA, G.A.; PICKETT, L.J.; FRACETO, L.F.;
CHAGAS, A.C.S. Nanoformulations with synthetic and plant-derived
compounds for cattle tick control. Veterinary Parasitology, v. 309, p.
109756, 2022.

**10.** SANTOS, I.B; **ANHOLETO, L.A.;** SOUSA, G.A.; NUCCI, A.S.;
GAINZA, Y.A.; FIGUEIREDO, A.; SANTOS, L.A.L.; MINHO, A.P.;
BARIONI-JUNIOR, W.; ESTEVES, NOVITA, S.; NICIURA, S.C.M.; CHAGAS, A.C.S.
Investigating the benefits of targeted selective treatment according to
average daily weight gain against gastrointestinal nematodes in Morada
Nova lambs. Parasitology Research, 2022.

**11.** LIMA-DUARTE, L.; CASTRO-SANTIAGO, A.C.; CAMARGO, J.V.; FERRETTI,
A. B. S. M.; **ANHOLETO, L. A.**; PEREIRA, M. C.; IKEDA, P.; PEREZ, C.
A.; SANCHES, G. S.; CAMARGO-MATHIAS, M. I.; MELLO, D. C. C.; MACHADO, R.
Z.; ANDRE, M. R.; BATTESTI, D. M. B. Establishment and multiapproach
characterization of *Amblyomma sculptum* (Acari: Ixodidae) cell line
(ASE-14) from Brazil. Ticks and Tick-Borne Diseases, 2022.

**12.** LIMA DE SOUZA, J.R.; OLIVEIRA, P.R.; **ANHOLETO, L.A.**;
SODELLI, L.F.; FERREIRA, A.R.F.; REMEDIO, R.N.; CAMARGO-MATHIAS, M.I.
The bioactive compound carvacrol as a potential acaricide: An assessment
of its effects on the integument of female sensu lato ticks. Microscopy
Research and Technique, p. 1-7, 2021.

**13.** LIMA-DUARTE, L.; CAMARGO, J.V.; CASTRO-SANTIAGO, A.C.; MACHADO,
R.Z.; ADRRÉ, M.R.; CABRAL-DE-MELLO, D.C.; CAMARGO-MATHIAS, M.I.; IKEDA,
P.; **ANHOLETO, L.A.;** PEREIRA, M.C.; COSTA, A.J.; BARROS-BATTESTI,
D.M. Establishment and characterization of a cell line (RBME-6) of
*Rhipicephalus (Boophilus) microplus* from Brazil. Ticks and Tick-borne
Diseases, 12(5), 101770, 2021. DOI:
https://doi.org/10.1016/j.ttbdis.2021.101770.

**14.** DORIGO, A. S.\*; ANJOS, A.\*; MARCATO, A.C.C.\*; PIRES-SILVA,
D.\*; Gonçalves, L. R.\*; **ANHOLETO, L. A.\*;** CHOLAK, L. R.\*;
RAMALHO, M. O.\*; BORBA, R. S.\*; ORTELANI, M. P.; CABRAL-DE-MELO, D. C.
Projeto Primeiros Passos na Ciência: Rompendo barreiras sociais e
estreitando laços entre a comunidade acadêmica e o Ensino Médio público.
Revista Brasileira de Extensão Universitária, 11(1), 47-59, 2020. DOI:
https://periodicos.uffs.edu.br/index.php /RBEU/article/ view/10768/pdf
(\* shared first authorship).

**15.** KONIG, ISAAC FILIPE MOREIRA; OLIVEIRA, MARCOS VINÍCIUS SILVA;
GONÇALVES, RAQUEL ROMANO PALMEIRA; PECONICK, ANA PAULA; THOMASI, SÉRGIO
SCHERRER; **ANHOLETO, LUÍS ADRIANO**; LIMA-DE-SOUZA, JOSÉ RIBAMAR;
CAMARGO-MATHIAS, MARIA IZABEL; NEODINI REMEDIO, RAFAEL. Low
concentrations of acetylcarvacrol induce drastic morphological damages
in ovaries of surviving Rhipicephalus sanguineus sensu lato ticks
(Acari: Ixodidae). **Micron**. v.129, p. 102780, 2019. DOI:
http://dx.doi.org/10.1016/j.micron.2019.102780.

**16.** OLIVEIRA, PATRÍCIA ROSA; **ANHOLETO, LUIS ADRIANO**; FERREIRA,
RODNEY ALEXANDRE RODRIGUES; ARNOSTI, ANDRÉ; BECHARA, GERVÁSIO HENRIQUE;
CASTRO, KARINA NEOOB CARVALHO; CAMARGO-MATHIAS, MARIA IZABEL. Cytotoxic
effects of extract of *Acmella olerace*a in the ovaries and midgut of
*Rhipicephalus sanguineus* Latreille, 1806 (Acari: Ixodidae) female
ticks. **Journal of Microscopy and Ultrastructure**, v.7, p.28, 2019.
DOI: http://dx.doi.org/10.4103/jmau.jmau_16_18

**17.** SOUZA, JOSÉ RIBAMAR LIMA; OLIVEIRA, PATRÍCIA ROSA; **ANHOLETO,
LUÍS ADRIANO**; ARNOSTI, ANDRÉ; PINTO, ERIK DAEMON SOUZA; REMEDIO,
RAFAEL NEODINI; CAMARGO-MATHIAS, MARIA IZABEL. Effects of carvacrol on
oocyte development in semi-engorged *Rhipicephalus sanguineus* sensu
lato females ticks (Acari: Ixodidae). **Micron**, v.116, p.66 - 72,
2018. DOI: http://dx.doi.org/10.1016/j.micron.2018.09.015

**18.ANHOLETO, LUÍS ADRIANO**; OLIVEIRA, PATRÍCIA ROSA; RODRIGUES,
RODNEY ALEXANDRE FERREIRA; YAMANE, LAIS THIEMI; CASTRO, KARINA NEOOB DE
CARVALHO; CAMARGO-MATHIAS, MARIA IZABEL. Morphological alterations in
the ovaries of semi-engorged ticks exposed to ethanolic extract of
*Acmella oleracea*. **Microscopy Research and Technique**, v.1, p.1-11,
2018. DOI: http://dx.doi.org/10.1002/jemt.23145

**19.** ABREU, RUSLEYD MARIA MAGALHÃES; ABREU, MARINA RODRIGUES; SANTOS,
JUAN PARENTE; HEBLING, LETÍCIA MARIA GRABALLHOS FERRAZ; **ANHOLETO, LUÍS
ADRIANO**; SOUZA, JOSÉ RIBAMAR LIMA; CAMARGO-MATHIAS, MARIA IZABEL.
Morphological evaluation of the liver in Wistar rats inoculated with
(Latreille, 1806) (Acari: Ixodidae) salivary gland extracts.
**Microscopy Research and Technique**, v.81, p.1332-1338, 2018. DOI:
http://dx.doi.org/10.1002/jemt.23142

**20.** OLIVEIRA, PATRÍCIA ROSA; **ANHOLETO, LUIS ADRIANO**; RODRIGUES,
RODNEY ALEXANDRE FERREIRA; BECHARA, GERVÁSIO HENRIQUE; CASTRO, KARINA
NEOOB CARVALHO; CAMARGO-MATHIAS, MARIA IZABEL. The potential of *Acmella
oleracea* (Jambu) extract in the control of semi-engorged *Rhipicephalus
sanguineus* (Latreille, 1806) (Acari: Ixodidae) female ticks.
**International** **Journal of Acarology**, v.44, p.192-197, 2018. DOI:
https://doi.org/10.1080/01647954.2018.1472637

**21.ANHOLETO, LUÍS ADRIANO**; OLIVEIRA, PATRÍCIA ROSA; RODRIGUES,
RODNEY ALEXANDRE FERREIRA; YAMANE, LAIS THIEMI; CASTRO, KARINA NEOOB
CARVALHO; CAMARGO-MATHIAS, MARIA IZABEL. Toxic action of *Acmella
oleracea* extract on the male reproductive system of *Amblyomma
cajennense* ticks. **Veterinary Parasitology**, v.244, p.164 - 171,
2017. DOI: http://dx.doi.org/10.1016/j.vetpar.2017.07.031

**22.** YAMANE, LAIS THIEMI; PAULA, ENEIDA; JORGE, MICHELLE PEDROZA;
FREITAS-BLANCO, VERÔNICA SANTANA; JUNIOR, ÍLIO MONTANARI; FIGUEIRA, GLYN
MARA; **ANHOLETO, LUÍS ADRIANO**; OLIVEIRA, PATRICIA ROSA; RODRIGUES,
RODNEY ALEXANDRE FERREIRA. *Acmella oleracea* and *Achyrocline
satureioides* as sources of natural products in topical wound care.
**Evidence-Based Complementary and Alternative Medicine**, v.2016, p.1 -
9, 2016. DOI: http://dx.doi.org/10.1155/2016/3606820

**23.** OLIVEIRA, PATRÍCIA ROSA; CASTRO, KARINA NEOOB CARVALHO;
**ANHOLETO, LUIS ADRIANO**; CAMARGO MATHIAS, MARIA IZABEL. Cytotoxic
effects of extract of *Acmella oleraceae* (Jambú) in *Rhipicephalus
microplus* females ticks. **Microscopy Research and Technique**, p.744 -
753, 2016. DOI: http://dx.doi.org/10.1002/jemt.22693

**24.** OLIVEIRA, PATRÍCIA ROSA; **ANHOLETO, LUIS ADRIANO**; BECHARA,
GERVÁSIO HENRIQUE; MATHIAS, MARIA IZABEL CAMARGO. Dinotefuran-induced
morphophysiological changes in semi-engorged females *Rhipicephalus
sanguineus* Latreille, 1806 (Acari: Ixodidae) ticks: Ultra-structural
evaluation. **Acta Tropica**, v.166, p.139 - 154, 2016. DOI:
http://dx.doi.org/10.1016/j.actatropica.2016.11.017

**25.** REMEDIO, RAFAEL NEODINI.; NUNES, PABLO HENRIQUE; **ANHOLETO,
LUÍS ADRIANO**; OLIVEIRA, PATRICIA ROSA; SÁ, I.C.G.; CAMARGO-MATHIAS,
MARIA IZABEL. Morphological alterations in salivary glands of
*Rhipicephalus sanguineus* ticks (Acari: Ixodidae) exposed to neem seed
oil with known azadirachtin concentration. **Micron**, v.83, p.19-31,
2016. DOI: http://dx.doi.org/10.1016/j.micron.2016.01.004

**26.ANHOLETO, LUÍS ADRIANO**; OLIVEIRA, PATRÍCIA ROSA; RODRIGUES,
RODNEY ALEXANDRE FERREIRA; SPINDOLA, CAROLINE DOS SANTOS; LABRUNA,
MARCELO BAHIA; PIZANO, MARCOS APARECIDO; CASTRO, KARINA NEOOB DE
CARVALHO; CAMARGO-MATHIAS, MARIA IZABEL. Potential action of extract of
*Acmella oleracea* (L.) R.K. Jansen to control *Amblyomma cajennense*
(Fabricius, 1787) (Acari: Ixodidae) ticks. **Ticks and Tick-Borne
Diseases**, v.8, p.65 - 72, 2016. DOI:
http://dx.doi.org/10.1016/j.ttbdis.2016.09.018

**27.** PEREIRA, MELISSA CAROLINA.; NODARI, ELEN FERNANDA.; **ANHOLETO,
LUIS ADRIANO**.; CAMARGO-MATHIAS, MARIA IZABEL. The use of
imidazole-osmium (C3H4N2/OsO4) to stain lipids in salivary gland
histological sections of *Rhipicephalus sanguineus* sensu lato (Acari:
Ixodidae) female ticks. **The Journal of Basic & Applied Zoology**,
v.74, p.68 - 74, 2016. DOI:
http://dx.doi.org/10.1016/j.jobaz.2016.10.004

**28.** OLIVEIRA, PATRÍCIA ROSA; REMÉDIO, RAFAEL NEODINI; BECHARA,
GERVÁSIO HENRIQUE; **ANHOLETO, LUIS ADRIANO**; CAMARGO-MATHIAS, MARIA
IZABEL. Dinotefuran-induced morphophysiological changes in the ovaries
and midgut of semi-engorged females *Rhipicephalus sanguineus*
Latreille, 1806 (Acari: Ixodidae) ticks. **Parasitology Research**, v.
115 p.829-849, 2016. DOI: http://dx.doi.org/10.1007/s00436-015-4814-3

**29.** REMEDIO, RAFAEL NEODINI; NUNES, PABLO HENRIQUE; **ANHOLETO, LUIS
ADRIANO**; CAMARGO-MATHIAS, MARIA IZABEL. Morphological alterations in
the synganglion and integument of *Rhipicephalus sanguineus* ticks
exposed to aqueous extracts of neem leaves (*Azadirachta indica* A.
JUSS). **Microscopy Research and Technique**, v. 77, p. 989-998, 2014.
DOI: https://doi.org/10.1002/jemt.22427

**30.** REMEDIO, RAFAEL NEODINI; NUNES, PABLO HENRIQUE**; ANHOLETO, LUIS
ADRIANO**; OLIVEIRA, PATRICIA ROSA; CAMARGO-MATHIAS, MARIA IZABEL.
Morphological effects of neem (*Azadirachta indica* A. Juss) seed oil
with known azadirachtin concentrations on the oocytes of semi-engorged
*Rhipicephalus sanguineus* ticks (Acari: Ixodidae). Parasitology
Research, v.114, p. 431-444 , 2015. DOI:
http://dx.doi.org/10.1007/s00436-014-4200-6

**31.** ABREU, MARINA RODRIGUES.; ROCHA, FABIANA ALONSO; FURQUIM, KARIM
CHRISTINA SCOPINHO; **ANHOLETO, LUÍS ADRIANO;** NOVAES, FABIANA CRISTINA
FUZARO; MORSOLETO, MARIA JOSÉ; CAMARGO-MATHIAS, MARIA IZABEL. Salivary
glands of female ticks *Rhipicephalus sanguineus* like a potential
source of molecules with inhibitory action: *in vivo* study with Walker
256 Tumor Cells. **Journal of Pharmaceutical Care & Health Systems**,
v.1, p.1 - 4, 2014. DOI: 10.4172/2376-0419.1000121

**32.ANHOLETO, LUÍS ADRIANO**; NUNES, PABLO HENRIQUE; REMÉDIO, RAFAEL
NEODINI; CAMARGO-MATHIAS, MARIA IZABEL. Testes of fed and unfed
*Amblyomma cajennense* ticks (Acari: Ixodidae). First morphological
data. **Acta Zoologica**, v. 96, p. 375-382, 2014. DOI:
https://doi.org/10.1111/azo.12083

**33.** REMEDIO, RAFAEL NEODINI; SAMPIERI, BRUNO RODRIGUES; VENDRAMINI,
MARIA CLAUDIA RAMALHO.; SOUZA, NATALIA MARQUESINI; DENARDO, **ANHOLETO,
LUIS ADRIANO**; T. A. G. B.; CAMARGO-MATHIAS, MARIA IZABEL. Morphology
of the midgut of *Rhipicephalus sanguineus* (Latreille, 1806) (Acari:
Ixodidae) adult ticks in different feeding stages. **Parasitology
Research**, v.112, p.415 - 425, 2013. DOI:
http://dx.doi.org/10.1007/s00436-012-3153-x

## **Books chapter**

**1. ANHOLETO, L.A.;** OLIVEIRA, P.R.; RODRIGUES, R.A.F; CASTRO, K.N.C.;
CAMARGO-MATHIAS, M.I. AÇÃO DO EXTRATO ETANÓLICO BRUTO DE *Acmella
oleracea* EM CARRAPATOS *Amblyomma cajennense* (ACARI: IXODIDAE):
AVALIAÇÃO ULTRAESTRUTURAL DO SISTEMA REPRODUTOR MASCULINO In:
**Biodiversidade e Biotecnologia no Brasil 2**. 1 ed.: Stricto Sensu
Editora, 2020, p. 71-89.

**2.** OLIVEIRA, P. R.; **ANHOLETO, L. A.;** CONTIERO, J.; ROCHA, C. Q.;
MONTEIRO, O. S.; CAMARGO-MATHIAS, M. I. Ramnolipídios no controle de
pragas de importância médica-veterinária In: **Saúde do Ensino à
Pesquisa**. 1 ed. Irati: Pasteur, 2020, v.1, p. 307-316.

**3.** SOUZA, J. R. L. ; OLIVEIRA, P. R. ; **ANHOLETO, L. A.** ;
SODELLI, L. F. ; REMEDIO, R. N. ; DEMETRIO, C. G. B. ; RIBEIRO JUNIOR,
E. E. ; CAMARGO-MATHIAS, M. I. . **Determinação da concentração letal
média (CL50) do bioativo carvacrol para uso no controle de carrapatos
*Rhipicephalus sanguineus* sensu lato (Acari: Ixodidae)**. In: Dionatas
Ulises de Oliveira Meneguetti, Romeu Paulo Martins Silva. (Org.).
**Ciência da Saúde na Amazônia Ocidental 2**. 1ed.Rio Branco, Acre:
Stricto Sensu Editora, 2019, v. 2, p. 74-87.

**4.** ABREU, M. R. ; TRAVAGLINI, R. V. ; OLIVEIRA, P. R. ; **ANHOLETO,
L. A.** ; MATOS, R. S. ; SANCHES, G. S. ; CAMARGO-MATHIAS, M. I. **.
Ticks On The Magnifying Glass**. In: Maria Izabel Camargo Mathias.
(Org.). **Inside Ticks Morphophysiology, Toxicology and Therapeutic
Perspectives**. 1ed.São Paulo: Editor UNESP, 2018, v. 1, p. 33-45.

**5.** FURQUIM, K. C. S. ; **ANHOLETO, L. A.** ; NODARI, E. F. ; ABREU,
M. R. ; CAMARGO-MATHIAS, M. I. . **Salivary Glands In *Rhipicephalus
sanguineus* s. l. Ticks: Morphostructural Complexity And Functional
Diversity**. In: Maria Izabel Camargo Mathias. (Org.). **Inside Ticks
Morphophysiology, Toxicology and Therapeutic Perspectives**. 1ed.São
Paulo: Editora UNESP, 2018, v. 1, p. 52-72.

**6.** OLIVEIRA, P. R. ; **ANHOLETO, L.A.** ; PEREIRA, N. R. C. ;
FERREIRA, A. R. F. ; CAMARGO-MATHIAS, M. I. . **Generating New
Individuals I (Female Reproductive System)**. In: Maria Izabel Camargo
Mathias. (Org.). **Inside Ticks Morphophysiology, Toxicology and
Therapeutic Perspectives**. 1ed.São Paulo: Editor UNESP, 2018, v. 1, p.
87-96.

**7. ANHOLETO, L.A.**; SAMPIERI, B. R. ; CAMARGO-MATHIAS, M. I. .
**Generating New Individuals II (Male Reproductive System).** In: Maria
Izabel Camargo Mathias. (Org.). **Inside Ticks Morphophysiology,
Toxicology and Therapeutic Perspectives.** 1ed.São Paulo: Editora UNESP,
2018, v. 1, p. 97-102.

**8.** OLIVEIRA, P. R. ; NODARI, E. F. ; PEREIRA, M. C. ; PEREIRA, N. R.
C. ; **ANHOLETO, L. A.** ; ABREU, M. R. ; OLIVEIRA, S. A. R. ; ARNOSTI,
A. ; SANTOS, J. P. ; CAMARGO-MATHIAS, M. I. **. Synthetic Acaricides**.
In: Maria Izabel Camargo Mathias. (Org.). **Inside Ticks
Morphophysiology, Toxicology and Therapeutic Perspectives.** 1ed.São
Paulo: Editora UNESP, 2018, v. 1, p. 116-162.

**9**. OLIVEIRA, P. R. ; **ANHOLETO, L. A.** ; LIMA-SOUZA, J. R. ;
REMEDIO, R. N. ; MATOS, R. S. ; CUNHA, E. L. R. ; ARNOSTI, A. ;
SAMPIERI, B. R. ; SODELLI, L. F. ; OLIVEIRA, S. A. R. ; CAMARGO-MATHIAS,
M. I. . **Natural Acaricides**. In: Maria Izabel Camargo Mathias.
(Org.). **Inside Ticks Morphophysiology, Toxicology and Therapeutic
Perspectives**. 1ed.São Paulo: Editora UNESP, 2018, v. 1, p. 163-190.

**10**. FURQUIM, K. C. S. ; **ANHOLETO, L. A.** ; ABREU, M. R. ;
CAMARGO-MATHIAS, M. I. . **A New View On The Biosynthetic/Secretory
Plurality Of The Salivary Glands: Bioactive Molecules In *Rhipicephalus
sanguineus* s. l..** In: Maria Izabel Camargo Mathias. (Org.). **Inside
Ticks Morphophysiology, Toxicology and Therapeutic Perspectives.**
1ed.São Paulo: Editora UNESP, 2018, v. 1, p. 191-222.

**11. ANHOLETO, L. A.**; OLIVEIRA, P. R. ; LIMA-SOUZA, J. R. ; ABREU, R.
M. M. ; NODARI, E. F. ; PEREIRA, M. C. ; CALLIGARIS, I. B. ;
CAMARGO-MATHIAS, M. I. **Microscopic Techniques Applied In Tick
Research**. In: Maria Izabel Camargo-Mathias. (Org.). **Inside Ticks:
Morphophysiology, Toxicology and Therapeutic Perspectives**. 1ed.São
Paulo: Editor UNESP, 2018, v. 1, p. 13-32.

## **Magazines**

**ANHOLETO, L.A.**; FARAONE, NICOLETTA. The use of repellents and
acaricides of natural origin against ticks: a One Health approach.
**Revista A Flora**. Rio de Janeiro, p.5 - 8, 2023.

**ANHOLETO, L. A.;** CAMARGO-MATHIAS, M. I.; OLIVEIRA, P. R.; RODRIGUES,
R. A. F.; CASTRO, K. N. C.

Eclectic plant. **Revista Pesquisa FAPESP**. São Paulo, SP, p.72 - 73,
2018.

## **Media coverage**

**“Tick-killing fungus research underway at N.S. university”**, 2024,
CBC, Nova Scotia, Canada.

## **Congress abstracts**

**1.ANHOLETO, L. A.;** BRANCAGLION, G. A.; SANTOS, D. M.; KAPRITCHKOFF,
R. T. I.; CASTRO, KARINA NEOOB DE CARVALHO; CANUTO, K. M.; RODRIGUES, R.
A. F.; CORREA, D. S.; PASTRE, J. C.; CHAGAS, A. C. S. Acaricide activity
of the synthetic derivative of espilantol against ticks of medical and
veterinary importance In: XV Jornada Científica – Embrapa de São Carlos,
2023, São Carlos. Anais da XV Jornada Científica – Embrapa de São
Carlos, 2023. p.1 – 66.

**2.ANHOLETO, L. A.;** BLANCHARD, S.; CHAGAS, A. C. S.; HILLIER, N. K.;
FARAONE, N. In vitro evaluation of essential oils and their binary
mixtures against the black-legged ticks Ixodes scapularis (Acari:
Ixodidae) In: XIV Brazilian Symposium on Pharmacognosy, 2023, São Luis.
Livro de Resumos - Apresentações Orais e Pôsteres, 2023. v.1.

**3.** KAPRITCHKOFF, R. T. I.; **ANHOLETO, L. A.;** CHAGAS, A. C. S.
Determination of the frequency of haplotypes of sheep B-globin and
comparison with phenotypic characteristics in sheep of the Santa Inês,
Texel and White Dorper breeds submitted to natural infection by
*Haemonchus contortus.* In: 14a. Jornada Científica Embrapa São Carlos,
2022, São Carlos.  Anais da 14a. Jornada Científica Embrapa São Carlos.
São Carlos: Embrapa, 2022.

**4.** CHAGAS, A. C. S.; **ANHOLETO, L. A.;** KAPRITCHKOFF, R. T. I.;
DOS SANTOS, ISABELLA BARBOSA; ESTEVES, SÉRGIO NOVITA. *Haemonchus
contortus* replacement in a sheep flock as an approach to control
anthelmintic resistance In: 73rd Annual Meeting of the European
Federation of Animal Science, 2022, Porto. Book of Abstracts of the 73rd
Annual Meeting of the European Federation of Animal Science. The
Netherlands: Wageningen Academic Publishers, 2022.

**5.** CHAGAS, A. C. S.; DOS SANTOS, ISABELLA BARBOSA; FERREIRA, A. U.
C.; RABELO, M. D.; **ANHOLETO, L. A.;** ESTEVES, SÉRGIO NOVITA.
Relationship between packed cell volume and gastrointestinal nematodes
in sheep through NIRS In: 73rd Annual Meeting of the European Federation
of Animal Science, 2022, Porto.  Book of Abstracts of the 73rd Annual
Meeting of the European Federation of Animal Science. The Netherlands:
Wageningen Academic Publishers, 2022.

**6.ANHOLETO, L. A.;** CAMARGO MATHIAS, MARIA IZABEL; OLIVEIRA, P. R.;
RODRIGUES, RODNEY ALEXANDRE FERREIRA; YAMANE, LAIS THIEMI; CASTRO,
KARINA NEOOB DE CARVALHO. Toxic action of Acmella oleracea extract on
the *Amblyomma cajennense* (Acari: Ixodidae) male reproductive system
In: III Latin American Congress of Acarology and VI Brazilian Symposium
of Acarology, 2018, Pirenópolis, Goiás.  Congress proceedings of III
CLAC & VI SIBAC, 2018.

**7.ANHOLETO, L. A.;** CAMARGO-MATHIAS, M. I.; MORAES, K. C. M.; ABREU,
M. R. Action of *Rhipicephalus sanguineus* (Latreille, 1806) salivary
gland extract on HEP-G2 tumor cells. In: IX Scientific Symposium of
Postgraduates in CENA, 2016. Resumos dos trabalhos apresentados no IX
Simpósio Científico dos Pós-graduandos no CENA. Piracicaba - SP: Seção
Técnica de Biblioteca - CENA/USP, 2016. v.1.

**8.** ABREU, M. R.; CAMARGO-MATHIAS, M. I.; ROCHA, F. A.; FURQUIM, K.
C. S.; **ANHOLETO, L.A.**; NOVAES, F. C. F.; MORSOLETO, M. J.; NODARI,
E. F. Action of the salivary gland extract of female ticks
*Rhipicephalus sanguineus* on the morphology of tumour cells of Walker
256. In: II Congreso Latinoamericano de Acarología, 2016, Montenegro,
Quindío, Colombia. II Congreso Latinoamericano de Acarología II Clac.
Vol. 2. Montenegro, Quindío, Colombia: Sociedad Latinoamericana de
Acarología, 2016. v.2. p.63 - 63

**9.** PEREIRA, N. R. C.; CAMARGO-MATHIAS, M. I.; PEREIRA, M. C.;
NODARI, E. F.; **ANHOLETO, L. A.;** SANTOS, J. P. Morphophysiological
changes in the ovaries of ticks *Rhipicephalus sanguineus* (Acari:
Ixodidae) induced by Deltamethrin.  In: IX Scientific Symposium of
Postgraduates in CENA, 2016. Resumos dos trabalhos apresentados no IX
Simpósio Científico dos Pós-graduandos no CENA. Piracicaba - SP: Seção
Técnica de Biblioteca - CENA/USP, 2016. v.1.

**10.** PEREIRA, M. C.; CAMARGO-MATHIAS, M. I.; NODARI, E. F.;
**ANHOLETO, L.A.**; FURQUIM, K. C. S. Imidazole-osmium to stain lipids
in histological sections of *Riphicephalus sanguineus* s.l. salivary
glands In: II Congreso Latinoamericano de Acarología, 2016, Montenegro,
Quindío, Colombia.  Proceedings II Congreso Latinoamericano de
Acarología II Clac. Vol. 1. Montenegro, Quindío, Colombia: Sociedad
Latinoamericana de Acarología, 2016. v.1. p.51 – 52.

**11.** MATOS, R. S.; CAMARGO-MATHIAS, M. I.; DAEMON, E.; **ANHOLETO,
L.A.;** OLIVEIRA, P. R.; CRUZ, P. B.; DELMONTE, C. C.; ARNOSTI, A.;
SAMPIERI, B. R. Morphological analysis and lipid presence on Gene's
organ of *Rhipicephalus sanguineus* sensu lato (Acari: Ixodidae) exposed
thymol In: II Congreso Latinoamericano de Acarología, 2016, Montenegro,
Quindío, Colombia. Proceedings II Congreso Latinoamericano de Acarología
II Clac. Vol. 2. Montenegro, Quindío, Colombia: Sociedad Latinoamericana
de Acarología, 2016. v.2. p.65 – 65.

**12.** PEREIRA, M. C.; CAMARGO-MATHIAS, M. I.; NODARI, E. F.;
**ANHOLETO, L.A.** Osmium-imidazole for marking lipids in histological
sections of salivary glands in females of ticks *Rhipicephalus
sanguineus* l.s. (Acari: Ixodidae) In: XXVIII UNESP Congress of
Scientific Initiation, 2016, Bauru, SP.  Anais do XXVIII Congresso de
Iniciação Científica da UNESP, 2016.

**13.ANHOLETO, L.A.;** CAMARGO-MATHIAS, M. I.; OLIVEIRA, P. R.;
RODRIGUES, R. A. F.; LABRUNA, M. B.; PIZANO, M. A.; CASTRO, K. N. C.
Potential action of extract of *Acmella oleracea* (L.) R. K. Jansen to
control Amblyomma cajennense (Fabricius, 1787) (Acari: Ixodidae) ticks
In: II Congreso Latinoamericano de Acarología, 2016, Montenegro,
Quindío, Colombia.  Proceedings II Congreso Latinoamericano de
Acarología II Clac. Vol. 2. Montenegro, Quíndio, Colombia: Sociedad
Latinoamericana de Acarología, 2016. v.2. p.45 - 45

**14.ANHOLETO, L.A.;** CAMARGO-MATHIAS, M. I.; OLIVEIRA, P. R.; PIZANO,
M. A.; REMEDIO, R. N.; BECHARA, GERVÁSIO HENRIQUE; ABREU, R. M. M.;
LIMA-SOUZA, J. R. Potential action of the chemical dinotefuran in the
control of semiengorged female ticks *Rhipicephalus sanguineus*
(Latreille, 1806) (Acari: Ixodidae) In: II Congreso Latinoamericano de
Acarología, 2016, Montenegro, Quindío, Colombia.  Proceedings II
Congreso Latinoamericano de Acarología II Clac. Vol. 2. Montenegro,
Quindío, Colombia: Sociedad Latinoamericana de Acarología, 2016. v.2.
p.46 – 46.

**15.** ABREU, R. M. M.; CAMARGO-MATHIAS, M. I.; ABREU, M. R.;
**ANHOLETO, L.A.;** SANTOS, J. P.; HEBLING, L. M. G. F.; PEREIRA, N. R.
C.; LIMA-SOUZA, J. R.; NODARI, E. F.; MATOS, R. S. Renal evaluation in
rats submitted to the extract of salivary gland from *Rhipicephalus
sanguineus* (Latreille, 1806) (Acari: Ixodidae) In: II Congreso
Latinoamericano de Acarología, 2016, Montenegro, Quindío, Colombia.
Proceedings II Congreso Latinoamericano de Acarología II Clac. Vol. 2.
Montenegro, Quindío, Colombia: Sociedad Latinoamericana de Acarología,
2016. v.2. p.64 - 64

**16.** LIMA-SOUZA, J. R.; CAMARGO-MATHIAS, M. I.; **ANHOLETO, L. A.;**
OLIVEIRA, P. R.; REMEDIO, R. N.; NUNES, P. H. Ultrastructural changes in
the salivary glands of *Rhipicephalus sanguineus* ticks exposed to neem
seed oil (Azadirachta indica) In: V SIBAC - Brazilian Symposium of
Acarology, 2015, São José do Rio Preto, Brazil.  Anais do V SIBAC.,
2015.

**17.ANHOLETO, L. A.;** REMEDIO, R. N.; NUNES, P. H.; OLIVEIRA, P. R.;
LIMA-SOUZA, J. R.; CAMARGO-MATHIAS, M. I. Morphological effects of neem
seed oil (*Azadiractha indica* A Juss) on the salivary glands of
semi-ingurgitate females of the tick *Rhipicephalus sanguineus* (Acari:
Ixodidae). In: V SIBAC - Brazilian Symposium of Acarology, 2015, São
José do Rio Preto. Anais do V SIBAC. , 2015.

**18.** ABREU, M. R.; CAMARGO-MATHIAS, M. I.; FURQUIM, K. C. S.; ROCHA,
F. A.; **ANHOLETO, L. A.;** NOVAES, F. C. F.; MORSOLETO, M. J. Salivary
glands of female ticks *Rhipicephalus sanguineus* like a potential
source of molecules with inhibitory action: in vivo study with walker
256 tumour cells In: The 2014 Pathology Congress, 2014, London, UK. The
2014 Pathology Congress Abstracts. Barnet: EuroSciCon LTDA UK, 2014.
v.1.

**19.** TEIXEIRA, L. D.; **ANHOLETO, L. A.**; DARIO, I. S. N.; DARIO, J.
G. A. Control of tomato bacterial spot with a new product: copper
sulphate pentahydrate. In: International Congress of Phytopathology,
2009, Rio de Janeiro - RJ.  Tropical Plant Pathology. Brasília:
Brazilian Phytopathological Society, 2009. v.34. p.103 – 103.

**20.ANHOLETO, L. A.;** VILELA, T. M.; DARIO, I. S. N.; DARIO, J. G. A.
Agronomic efficiency of a new product: pentahydrate copper sulphate in
the control of blackleg of potato crop. In: International Congress of
Phytopathology, 2009, Rio de Janeiro - RJ.  Tropical Plant Pathology.
Brasília: Brazilian Phytopathological Society, 2009. v.34. p.95 – 95.

## **ORAL PRESENTATIONS**

**1. ANHOLETO, L.A.;** FERGUSON, L.; HILLIER, K.; FARAONE, N. Effect of
temperature and humidity on tick response to repellents and acaricides:
implications of climate change for tick control strategies. Atlantic
Canada Association of Parasitologists (ACAP) Annual meeting 2024,
Wolfville, 2024.

**2.ANHOLETO, L.A.;** BLANCHARD, S.; CHAGAS, A.C.S., HILLIER, N.K.;
FARAONE, N. *In vitro*, evaluation of essential oils and their binary
mixtures against the black-legged ticks *Ixodes scapularis* (Acari:
Ixodidae). XIV Brazilian Symposium on Pharmacognosy, Maranhão, Brazil,
2023.

**3.ANHOLETO, L. A**.; BRANCAGLION, G. A.; SANTOS, D. M.; KAPRITCHKOFF,
R. T. I.; CASTRO, K. N. C.; CANUTO, K. M.; RODRIGUES, R. A. F.; CORREA,
D. S.; PASTRE, J. C.; CHAGAS, A. C. S. Atividade acaricida do derivado
sintético do espilantol contra carrapatos de importância médica e
veterinária. XV Jornada Científica da Embrapa de São Carlos, São Carlos,
Brazil, 2023.

**4.ANHOLETO, L.A**.; FIGUEIREDO, A.; COLA, D.; FANTATTO, R.R.; GAINZA,
Y.A.; SANTOS, I.B.; FRACETO, L.F.; HILLIER, N.K.; FARAONE, N.; CHAGAS,
A.C.S. Association of zein nanoparticles with botanical compounds for
cattle tick control. 2022 Joint ESA, ESC, and ESBC Annual Meeting,
Vancouver, British Columbia, Canada. Entomological Society of America
(ESA).

## **POSTER PRESENTATIONS**

**1.ANHOLETO, L.A.;** FERGUSON, L., FARAONE, N. Isolation and
identification of *Clonostachys rosea* (Ascomycota: Hypocreales) from
deceased ticks, revealing a novel natural tick pathogen. 63rd Annual
Meeting of the Canadian Society of Zoologists, Moncton, NB, Canada,
2024.

**2.ANHOLETO, L.A.;** FERGUSON, L., FARAONE, N. Isolation of
*Clonostachys rosea* (Ascomycota: Hypocreales) entomopathogenic fungus
from deceased ticks, revealing a novel natural tick pathogen. TickNet
Canada Scientific Symposium, Toronto, ON, Canada, 2023.

**3.ANHOLETO, L. A.;** CHOLAK, L. R.; BORBA, R. S.; MELLO, D. C. C.;
GONCALVES, L. R. . First Steps in Science: an experience of integration
between high school and research. Meeting of the Graduate Program in
Education - INTEGRAP, UNESP Rio Claro, SP, Brazil, 2019.

**4.ANHOLETO, L. A.;** CAMARGO-MATHIAS, M. I.; OLIVEIRA, P. R.;
RODRIGUES, R. A. F.; YAMANE, LAIS THIEMI; CASTRO, K. N. C. Toxic action
of *Acmella oleracea* extract on the *Amblyomma cajennense* (Acari:
Ixodidae) male reproductive system. II Latin American Congress of
Acarology/VI Brazilian Symposium of Acarology, 2018, Goiás, Brazil.

**5.ANHOLETO, L. A.;** CAMARGO-MATHIAS, M. I. ; OLIVEIRA, P. R. ;
RODRIGUES, R. A. F. ; LABRUNA, M. B. ; PIZANO, M. A. ; CASTRO, K. N. C.
. Potential action of extract of *Acmella oleracea* (L.) R. K. Jansen to
control *Amblyomma cajennense* (Fabricius, 1787) (Acari: Ixodidae)
ticks. II Latin American Congress of Acarology, Quindío, Colombia, 2016.

**6.ANHOLETO, L. A.;** CAMARGO-MATHIAS, M. I. ; OLIVEIRA, P. R. ;
PIZANO, M. A. ; REMEDIO, R. N. ; BECHARA, GERVÁSIO HENRIQUE ; ABREU, R.
M. M. ; LIMA-SOUZA, J. R. . Potential action of the chemical dinotefuran
in the control of semi engorged female ticks *Rhipicephalus sanguineus*
(Latreille, 1806) (Acari: Ixodidae). II Latin American Congress of
Acarology, Quindío, Colombia, 2016.

**7.** ABREU, M. R. ; CAMARGO-MATHIAS, M. I. ; ROCHA, F. A. ; FURQUIM,
K. C. S. ; **ANHOLETO, L. A.** ; NOVAES, F. C. F. ; MORSOLETO, M. J.;
NODARI, E. F. . Action of the salivary gland extract of female ticks
*Rhipicephalus sanguineus* on the morphology of Walker 256 tumour cells.
II Latin American Congress of Acarology, Quindío, Colombia, 2016.

**8.** ABREU, R. M. M. ; CAMARGO-MATHIAS, M. I. ; ABREU, M. R. ;
**ANHOLETO, L.A.** ; SANTOS, J. P. ; HEBLING, L. M. G. F. ; PEREIRA, N.
R. C. ; LIMA-SOUZA, J. R. ; NODARI, E. F. ; MATOS, R. S. . Renal
evaluation in rats submitted to the extract of salivary gland from
*Rhipicephalus sanguineus* (Latreille, 1806) (Acari: Ixodidae). II Latin
American Congress of Acarology, Quindío, Colombia, 2016.

**9.** MATOS, R. S. ; CAMARGO-MATHIAS, M. I. ; DAEMON, E. ; **ANHOLETO,
L.A.** ; OLIVEIRA, P. R. ; CRUZ, P. B. ; DELMONTE, C. C. ; ARNOSTI, A. ;
SAMPIERI, B. R. . Morphological analysis and lipid presence on Gene's
organ of *Rhipicephalus sanguineus* sensu lato (Acari: Ixodidae) exposed
thymol. II Latin American Congress of Acarology, Quindío, Colombia,
2016.

**10.** PEREIRA, M. C. ; CAMARGO-MATHIAS, M. I. ; NODARI, E. F. ;
**ANHOLETO, L.A.** ; FURQUIM, K. C. S. . Imidazole-osmium to stain
lipids in histological sections of *Riphicephalus sanguineus* s.l.
salivary glands. II Latin American Congress of Acarology, Quindío,
Colombia, 2016.

**11.** PEREIRA, M. C. ; NODARI, E. F. ; CAMARGO-MATHIAS, M. I. ;
**ANHOLETO, L. A.** Osmium-imidazole for lipid staining in histological
sections of salivary glands of tick females *Rhipicephalus sanguineus*
(Acari: Ixodid). XXVIII Congress of Scientific Initiation, UNESP Rio
Claro, 2016.

**12.ANHOLETO, L.A.;** CAMARGO-MATHIAS, M. I. ; MORAES, K. C. M. ;
ABREU, M. R. . Action of salivary gland extract of *Rhipicephalus
sanguineus* (Latreille, 1806) on tumor cells HEP-G2. IX Scientific
Symposium of Graduate Students CENA/USP, Piracicaba, Brazil, 2016.

**13.** PEREIRA, N. R. C. ; CAMARGO-MATHIAS, M. I. ; PEREIRA, M. C. ;
NODARI, E. F. ; **ANHOLETO, L.A**. ; SANTOS, J. P. . Morphophysiological
changes in the ovaries of *Rhipicephalus sanguineus* ticks (Acari:
Ixodidae) induced by Deltamethrin. IX Scientific Symposium of Graduate
Students CENA/USP, Piracicaba, Brazil, 2016.

**14.ANHOLETO, L. A.;** REMEDIO, R. N. ; NUNES, P. H. ; OLIVEIRA, P. R.
; LIMA-SOUZA, J. R. ; CAMARGO-MATHIAS, M. I. Morphological effects of
neem seed oil (*Azadiractha indica* A Juss) on the salivary glands of
semi-engorged females of the tick *Rhipicephalus sanguineus* (Acari:
Ixodidae). V SIBAC – Brazilian Symposium on Acarology, UNESP Rio Preto,
SP, Brazil, 2015.

**15.** LIMA-SOUZA, J. R. ; CAMARGO-MATHIAS, M. I. ; **ANHOLETO, L. A.**
; OLIVEIRA, P. R. ; REMEDIO, R. N. ; NUNES, P. H. . Ultrastructural
changes in the salivary glands of *Rhipicephalus sanguineus* ticks
exposed to neem seed oil (*Azadirachta indica*). V SIBAC – Brazilian
Symposium on Acarology, UNESP Rio Preto, SP, Brazil, 2015.

**16.** ABREU, M. R. ; ROCHA, F. A. ; FURQUIM, K. C. S. ; **ANHOLETO, L.
A.** ; NOVAES, F. C. F. ; CAMARGO-MATHIAS, M. I. . Salivary glands of
female ticks *Rhipicephalus sanguineus* like a potential source of
molecules with inhibitory action*: In vivo* study with Walker 256 tumour
cells. The 2014 Pathology Congress, London, 2014.

**17.** SOUZA, C. P. ; ARAUJO, C. S. T. ; **ANHOLETO, L. A.** ; SOUZA,
R. B. ; GUEDES, T. A. ; MARIN-MORALES, M. A. . Cytogenotoxic effects of
residual concentrations of the herbicide Trifluralin in *Allium cepa*.
Event: II Ecotoxicology Symposium, UNESP Rio Claro, SP, Brazil, 2014.

**18.** CAMARGO-MATHIAS, M. I. ; DENARDO, T. A. G. B. ; SOUZA, N. M. ;
**ANHOLETO, L. A.** ; VENDRAMINI, M. C. ; SAMPIERI, B. R. ; REMEDIO, R.
N. Comparative morphological study of the midgut of *Rhipicephalus
sanguineus* (Acari: Ixodidae) (Latreille, 1806) fed male and
semi-engorged female ticks. Event: *Ticks and Tck-borne Pathogens
International Conference –* TTP7, Zaragoza, Spain, 2011.

## **PATENT**

**ANHOLETO, L. A**.; CHAGAS, A. C. S. ; PASTRE, J. C. ; BRANCAGLION, G.
A. ; CORREA, D. S. ; SANTOS, D. M. ; CANUTO, K. M. ; CASTRO, K. N. C. ;
MINHO, A. P. ; BRITO, E. S. ; ALVES, T. C. ; RODRIGUES, R. A. F. ;
RODRIGUES, M. V. N. ; SANTOS, A. S. . Acaricidal and repellent
nanoemulsion. 2022, Brazil.

## **RESEARCH COLLABORATIONS**

**Dr. Alessandro Pelegrine Minho** (Department of Veterinary
Parasitology, Brazilian Agricultural Research Corporation, São Carlos,
Brazil).

**2019-Present.** Project title: BIODEFENSE - Development of alternative
methods to control ectoparasites of veterinary interest.

**Dr. Simone Cristina Méo Niciura and Dr. Ana Carolina de Souza Chagas**
(Department of Veterinary Parasitology, Brazilian Agricultural Research
Corporation, São Carlos, Brazil).

**2021-2026.** Project title: Parasite-host-environment approach to
control anthelmintic resistance in sheep flocks.

**Dr. Nicoletta Faraone and Dr. Kirk Hillier** (Department of Chemistry
and Department of Biology, Acadia University, Wolfville, Canada).

**2022-2023.** Project title: Nanotechnology applied for the development
of botanical acaricides and repellents against ticks of medical and
veterinary importance.

**Dr. Darci Moraes Barros Battesti** (Department of Pathology,
Reproduction and One Health, São Paulo State University, Jaboticabal,
Brazil).

2020-2022. Project title: Characterization of tick cell lines and their
use as a substrate for the growth, maintenance and protein expression
profile of *Anaplasma marginale*.

**Dr. Lesley Bell-Sakyi** (Institute of Infection, Veterinary and
Ecological Sciences, University of Liverpool, Liverpool, UK).

**2018-2019.** Project title: Acaricidal activity *in vitro* of
spilanthol against cell lines derived from acaricide-resistant and
acaricide-susceptible *Rhipicephalus microplus* ticks with or without
*Ehrlichia minasensis* infection.

**Dr. Maria Izabel Souza Camargo** (Department of Biology, São Paulo
State University, Rio Claro, Brazil)

**2015-2018.** Project title: Determination and cellular tracking of
direct and indirect actions of carvacrol and thymol as tick control
strategy of *Rhipicephalus sanguineus* (Acari: Ixodidae).

**2018-2019.** Project title: Unraveling the *Ehrlichia canis* life
cycle in the *Rhipicephalus sanguineus* (tropical lineage) tick: an
essential step to control canine ehrlichiosis.

## **GRANTS**

**Research grant (2024/2025):** Entomopathogenic fungus, *Clonostachys
rosea* (Ascomycota: Hypocreales), as a novel tick biocontrol agent
against *Ixodes scapularis* and *Dermacentor variabilis* ticks. CanLyme
Foundation. **30,000 CAD.**

**Research grant (2022/2023):** Nanotechnology applied for the
development of botanical acaricides and repellents against ticks of
medical and veterinary importance.The São Paulo Research Foundation,
FAPESP grant n. 2021/10004-0. R\$ 59,123.90 + US\$ 35,972.11 **=
64,482.25 CAD (total).**

**Research grant (2019/2022):** Antiparasitic and antimicrobial activity
of Spilanthol: the study of the effects on ticks of medical and
veterinary importance and against pathogens transmitted by them.The São
Paulo Research Foundation, FAPESP grant n. 2019/20185-1. **R\$
203,497.56 = 55,921.13 CAD.**

**Research grant (2018/2019):** Acaricidal activity *in vitro* of
spilanthol against cell lines derived from acaricide-resistant and
acaricide-susceptible *Rhipicephalus microplus* ticks with or without
*Ehrlichia minasensis* infection. The São Paulo Research Foundation,
FAPESP grant n. 2018/08166-9. **R\$ 7,860.00 + US\$ 10,205.56 =
15,844.57 CAD.**

**Research grant (2015-2019):** The acaricide action of Jambu (*Acmella
oleracea*): Study of the effects on morphophysiology of male and female
reproductive systems of *Amblyomma cajennense* (Fabricius, 1787) (Acari:
Ixodidae) ticks. The São Paulo Research Foundation, FAPESP grant n.
2015/01496-5. **R\$ 160,311.84 = 44,053.69 CAD.**

**Research grant (2013-2015):** Effect of the extract of salivary glands
of female *Rhipicephalus sanguineus* (Latreille, 1806) on inhibition and
proliferation of tumour cells. The São Paulo Research Foundation, FAPESP
grant n. 2013/00654-0. R\$ 22,825.44 = **6,272.43 CAD.**

## **PEER-REVIEWS FOR SCIENTIFIC JOURNALS**

International Journal of Acarology (2025 – present) – Taylor & Francis.

Parasites & Vectors (2018 – present) – BMC.

Acta Parasitologica (2023 present) – Springer.

Revista Brasileira de Parasitologia Veterinária (2023 – present) -
Colégio Brasileiro de Parasitologia Veterinária.

## **LEADERSHIP AND SERVICE**

Leader of the Graduate Students in the Graduate counsel for the Cell and
Molecular Biology Program, São Paulo State University, Rio Claro, SP,
Brazil. 2017- 2019 (2 times).

Leader of the students in the Permanent Research Commission of the
Biosciences Institute of São Paulo State University, Rio Claro, SP,
Brazil. 2017 – 2019 (2 times).

Organizer of First Steps in Science. 2017. *Founder of the Project*.

Organizer of XXIX UNESP Undergraduate Research Congress, São Paulo State
University, Brazil, 2017.

Organizer of V Symposium on Cell and Molecular Biology, Brazil, 2017.

Organizer of First Steps in Science. 2016. *Founder of the Project*.

Organizer of XXVIII UNESP Undergraduate Research Congress, Brazil, 2016.

Organizer of Workshop 40 Years of Graduate Studies at the Biosciences
Institute, Brazil, 2016.

Organizer of IV Symposium on Cell and Molecular Biology, Brazil, 2015.

Organizer of III Symposium on Cell and Molecular Biology, Brazil, 2013.

## **LANGUAGE SKILLS**

English (Advanced), Portuguese (native), Spanish (basic)

## **OTHER SKILLS**

IT:Applications: Microsoft Office Suite, Internet, Coreldraw
